export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const FETCH_FILTER_CHARACTERS = 'FETCH_FILTER_CHARACTERS';

export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_FILTER_LOCATIONS = 'FETCH_FILTER_LOCATIONS';


export const FETCH_EPISODES = 'FETCH_EPISODES';
export const FETCH_FILTER_EPISODES = 'FETCH_FILTER_EPISODES';

export const GET_TASKS = 'GET_TASKS';
export const UPDATE_TASK = 'UPDATE_TASK';
export const ADD_TASK_TO_STORAGE = 'ADD_TASK_TO_STORAGE';
