export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const FETCH_FILTER_CHARACTERS = 'FETCH_FILTER_CHARACTERS';

export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_FILTER_LOCATIONS = 'FETCH_FILTER_LOCATIONS';


export const FETCH_EPISODES = 'FETCH_EPISODES';
export const FETCH_FILTER_EPISODES = 'FETCH_FILTER_EPISODES';